// GENERATED by tools/gen_book_data.c -- do not hand-edit.
// Regenerate with: tools/gen_book_data <opening-file> [max_entries]
//
// The device-ready opening book: two parallel `const` (flash-resident,
// zero RAM cost) arrays, book_static_hashes[] sorted ascending so
// book.c's book_probe_static() can binary-search it, and
// book_static_moves[] holding each entry's move at the same index.
#ifndef BOOK_DATA_H
#define BOOK_DATA_H

#include <stdint.h>

#define BOOK_STATIC_COUNT 17492

extern const uint64_t book_static_hashes[BOOK_STATIC_COUNT];
extern const uint16_t book_static_moves[BOOK_STATIC_COUNT];

#endif
