// Opening-book lookup -- see book.h for the design rationale: a STATIC,
// flash-resident book (book_data.c, generated by tools/gen_book_data.c) for
// the real device, plus a DYNAMIC, RAM-hash-table book (this file's own
// book_load()) kept around purely for fast host-side iteration.
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "book.h"
#include "book_data.h"
#include "attacks.h"

int book_enabled = 0;
int book_entry_count = 0; // static + dynamic combined; see book_init()

// ---------------------------------------------------------------------------
// STATIC (device-ready) lookup: book_data.c's two parallel `const` arrays,
// hashes sorted ascending, searched with an ordinary binary search. `const`
// data like this is placed in flash by the linker, not RAM -- this is the
// entire reason the device-ready book can hold thousands of entries while
// the dynamic table below has to stay tiny on real hardware.
// ---------------------------------------------------------------------------
static Move book_probe_static(uint64_t hash) {
    int lo = 0, hi = BOOK_STATIC_COUNT - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2; // avoids (lo+hi) overflow; not that BOOK_STATIC_COUNT is remotely close to that here
        uint64_t mid_hash = book_static_hashes[mid];
        if (mid_hash == hash) return (Move)book_static_moves[mid];
        if (mid_hash < hash) lo = mid + 1;
        else hi = mid - 1;
    }
    return 0;
}

// ---------------------------------------------------------------------------
// DYNAMIC (host-only) lookup: a fixed-size open-addressing hash table,
// keyed directly by the position's own Zobrist hash (no separate hashing
// step needed -- the Zobrist hash is already a good, uniformly-distributed
// 64-bit key on its own). Linear probing: on a collision, just check the
// next slot, wrapping around the table. BOOK_TABLE_CAPACITY is a power of
// two so "index modulo capacity" can be a cheap bitmask instead of a
// division.
//
// Sized generously for host testing (a full megabyte -- 65536 slots x 16
// bytes each once struct padding is counted -- is nothing on a host);
// see book.h's top comment for why this entire section compiles OUT of a
// device build (ONDSEL_DEVICE_BUILD defined) instead of merely going
// unused -- that distinction matters a lot here, since "unused but still
// allocated" would still burn 1MB of the micro:bit's 128KB of RAM just by
// existing. book_probe_static() above is what actually ships to the
// device.
// ---------------------------------------------------------------------------
#ifndef ONDSEL_DEVICE_BUILD
#define BOOK_TABLE_CAPACITY 65536 // must stay a power of two
#define BOOK_TABLE_MASK (BOOK_TABLE_CAPACITY - 1)

typedef struct {
    uint64_t key;   // the position's Zobrist hash; 0 is used as "empty slot"
                    // (an astronomically unlikely real hash collision with 0
                    // is an accepted, standard trade-off -- same one
                    // transposition tables in real engines make)
    Move move;
    bool occupied;
} BookSlot;

static BookSlot book_table[BOOK_TABLE_CAPACITY];
static int dynamic_entry_count = 0;

// Inserts (key -> move) if this key isn't already present. First-seen wins
// on a duplicate (deterministic: depends only on file/parse order, not on
// hash-table internals) -- later book_load() calls or later lines in the
// same file that happen to reach a position already known simply don't
// overwrite it.
static void book_insert(uint64_t key, Move move) {
    uint64_t idx = key & BOOK_TABLE_MASK;
    for (int probes = 0; probes < BOOK_TABLE_CAPACITY; probes++) {
        BookSlot *slot = &book_table[idx];
        if (!slot->occupied) {
            slot->occupied = true;
            slot->key = key;
            slot->move = move;
            dynamic_entry_count++;
            book_entry_count++;
            return;
        }
        if (slot->key == key) return; // already known -- keep the first-seen move
        idx = (idx + 1) & BOOK_TABLE_MASK;
    }
    // Table completely full -- silently drop the insert rather than loop
    // forever or corrupt anything. With the current book sizes (a few
    // thousand lines at most) this never actually happens; it's a safety
    // net, not something the current book files can trigger.
}

static Move book_probe_dynamic(uint64_t hash) {
    uint64_t idx = hash & BOOK_TABLE_MASK;
    for (int probes = 0; probes < BOOK_TABLE_CAPACITY; probes++) {
        const BookSlot *slot = &book_table[idx];
        if (!slot->occupied) return 0; // empty slot -- definitely not in this table
        if (slot->key == hash) return slot->move;
        idx = (idx + 1) & BOOK_TABLE_MASK;
    }
    return 0;
}
#endif // ONDSEL_DEVICE_BUILD

void book_init(void) {
#ifndef ONDSEL_DEVICE_BUILD
    memset(book_table, 0, sizeof(book_table));
    dynamic_entry_count = 0;
#endif
    book_entry_count = BOOK_STATIC_COUNT; // the static book is always "loaded" -- it's baked into flash, not something to load
}

Move book_probe(const Board *b) {
    // Static (flash) book first -- it's what a real device build actually
    // relies on, and checking it first means a host match testing the
    // static book behaves identically to how the device would.
    Move m = book_probe_static(b->hash);
    if (m != 0) return m;
#ifndef ONDSEL_DEVICE_BUILD
    return book_probe_dynamic(b->hash);
#else
    return 0;
#endif
}

// ---------------------------------------------------------------------------
// PARSING: turns a line of standard algebraic notation ("1. d4 Nf6 2. c4
// e6 ...") into the actual Move values it describes, by replaying it move
// by move from the start position and, at each ply, finding which legal
// move matches the SAN token. This is the same approach (and largely the
// same code) as the host match harnesses' own SAN parser -- book.c needs
// its own copy since it's the one piece of "read real chess notation and
// turn it into engine moves" logic the engine itself has never needed
// before now (the engine only ever produces moves, it's never had to
// consume externally-written ones).
//
// All of this -- down to book_load() itself at the end of the file --
// exists purely to feed the DYNAMIC table above, so none of it is needed
// (or compiled) in a device build either.
// ---------------------------------------------------------------------------
#ifndef ONDSEL_DEVICE_BUILD
static int legal_moves_now(Board *b, Move *out) {
    int side = b->side_to_move;
    int opponent = side == WHITE ? BLACK : WHITE;
    generate_pseudo_moves(b, 0);
    MoveList *list = &move_pool[0];
    int n = 0;
    for (int i = 0; i < list->count; i++) {
        Move m = list->moves[i];
        UndoInfo undo;
        make_move(b, m, &undo);
        int king_sq = bb_lsb_index(b->piece_bb[piece_index(side, KING)]);
        if (!is_square_attacked(b, king_sq, opponent)) out[n++] = m;
        unmake_move(b, m, &undo);
    }
    return n;
}

static int square_from_name(const char *s) { return (s[0] - 'a') + (s[1] - '1') * 8; }

static Move parse_san(Board *b, const char *san_in) {
    char san[16];
    strncpy(san, san_in, sizeof(san) - 1);
    san[sizeof(san) - 1] = '\0';
    int len = (int)strlen(san);
    while (len > 0 && (san[len - 1] == '+' || san[len - 1] == '#')) san[--len] = '\0';

    Move candidates[218];
    int n = legal_moves_now(b, candidates);

    if (strcmp(san, "O-O") == 0) {
        for (int i = 0; i < n; i++) if (move_flag(candidates[i]) == MOVE_KING_CASTLE) return candidates[i];
        return 0;
    }
    if (strcmp(san, "O-O-O") == 0) {
        for (int i = 0; i < n; i++) if (move_flag(candidates[i]) == MOVE_QUEEN_CASTLE) return candidates[i];
        return 0;
    }

    int promo_piece = 0;
    char *eq = strchr(san, '=');
    if (eq) {
        switch (eq[1]) {
            case 'N': promo_piece = KNIGHT; break;
            case 'B': promo_piece = BISHOP; break;
            case 'R': promo_piece = ROOK; break;
            case 'Q': promo_piece = QUEEN; break;
        }
        *eq = '\0';
        len = (int)strlen(san);
    }

    int piece_type = PAWN;
    int p = 0;
    if (isupper((unsigned char)san[0])) {
        switch (san[0]) {
            case 'N': piece_type = KNIGHT; break;
            case 'B': piece_type = BISHOP; break;
            case 'R': piece_type = ROOK; break;
            case 'Q': piece_type = QUEEN; break;
            case 'K': piece_type = KING; break;
        }
        p = 1;
    }

    if (len - 2 < 0) return 0;
    int to_sq = square_from_name(&san[len - 2]);

    int disambig_file = -1, disambig_rank = -1;
    for (int i = p; i < len - 2; i++) {
        char c = san[i];
        if (c == 'x') continue;
        if (c >= 'a' && c <= 'h') disambig_file = c - 'a';
        else if (c >= '1' && c <= '8') disambig_rank = c - '1';
    }

    Move found = 0;
    int found_count = 0;
    for (int i = 0; i < n; i++) {
        Move m = candidates[i];
        int from = move_from(m), to = move_to(m);
        if (to != to_sq) continue;
        int8_t piece = b->mailbox[from];
        int mt = piece > 0 ? piece : -piece;
        if (mt != piece_type) continue;
        if (move_is_promotion(m) && promo_piece != 0 && move_promotion_piece_type(m) != promo_piece) continue;
        if (disambig_file >= 0 && (from % 8) != disambig_file) continue;
        if (disambig_rank >= 0 && (from / 8) != disambig_rank) continue;
        found = m;
        found_count++;
    }
    return found_count == 1 ? found : 0; // ambiguous/unmatched SAN -- skip this token rather than guess
}

// Strips a leading move-number token ("12." or "12...") the same way the
// host match harnesses' tokenizer does, since the book files are plain
// exported movetext (numbers included), not a pre-stripped move list.
static int tokenize_line(const char *line, char tokens[][16], int max_tokens) {
    char buf[2048];
    strncpy(buf, line, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = '\0';
    int count = 0;
    char *tok = strtok(buf, " \t");
    while (tok && count < max_tokens) {
        char *dot = strchr(tok, '.');
        if (dot) {
            int nl = (int)(dot - tok);
            bool is_num = nl > 0;
            for (int i = 0; i < nl; i++) if (!isdigit((unsigned char)tok[i])) is_num = false;
            if (is_num) {
                char *rest = dot + 1;
                if (*rest == '\0') { tok = strtok(NULL, " \t"); continue; }
                tok = rest;
            }
        }
        strncpy(tokens[count], tok, 15);
        tokens[count][15] = '\0';
        count++;
        tok = strtok(NULL, " \t");
    }
    return count;
}

#define BOOK_MAX_LINE_PLIES 32

int book_load(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return 0;

    int before_count = book_entry_count;
    char line[2048];
    while (fgets(line, sizeof(line), f)) {
        size_t len = strlen(line);
        while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r')) line[--len] = '\0';
        if (len == 0) continue;

        char tokens[BOOK_MAX_LINE_PLIES][16];
        int n_tokens = tokenize_line(line, tokens, BOOK_MAX_LINE_PLIES);

        Board b;
        board_reset(&b);
        for (int i = 0; i < n_tokens; i++) {
            Move m = parse_san(&b, tokens[i]);
            if (m == 0) break; // parse failure -- stop walking this line, keep whatever was already inserted from it

            // Record BEFORE making the move: this position's hash maps to
            // the move that was actually played from here in this line.
            book_insert(b.hash, m);

            UndoInfo undo;
            make_move(&b, m, &undo);
        }
    }
    fclose(f);
    return book_entry_count - before_count;
}
#endif // ONDSEL_DEVICE_BUILD
